# Tensorflow2.0 小练习

In [1]:
import tensorflow as tf
import numpy as np

I0000 00:00:1774164907.062149   17334 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1774164923.078905   17334 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1774164935.296380   17334 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


## 实现softmax函数

In [2]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    x = tf.convert_to_tensor(x,dtype = tf.float32)

    #保证数值稳定
    x_max = tf.reduce_max(x, axis=-1, keepdims=True)
    x = x - x_max

    #计算exp
    exp_x =tf.exp(x)

    #归一化
    sum_exp = tf.reduce_sum(exp_x, axis=-1, keepdims=True)
    prob_x = exp_x / sum_exp
    ##########
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

E0000 00:00:1774164940.072968   17334 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [3]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    x = tf.convert_to_tensor(x,dtype = tf.float32)
    prob_x = 1.0 / (1.0 + tf.exp(-x))

    ##########
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [6]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    x = tf.convert_to_tensor(x, dtype=tf.float64)
    label = tf.convert_to_tensor(label, dtype=tf.float64)

    eps = 1e-9
    x = tf.clip_by_value(x, eps, 1.0)

    #计算交叉熵
    loss = -tf.reduce_sum(label * tf.math.log(x), axis=-1)
    loss = tf.reduce_mean(loss)
    ##########
    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

np.True_

## 实现 sigmoid 交叉熵loss函数

In [8]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    x = tf.convert_to_tensor(x, dtype=tf.float64)
    label = tf.convert_to_tensor(label, dtype=tf.float64)

    eps = 1e-9
    x = tf.clip_by_value(x, eps, 1.0)

    #计算交叉熵
    loss = - (label * tf.math.log(x) + (1 - label) * tf.math.log(1 - x))
    loss = tf.reduce_mean(loss)
    ##########
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[1. 1. 1. 0. 0. 0. 1. 0. 1. 0.]


np.True_